name: Run AnghaBench CI Tests

on:
  # Run this workflow every day at 3am
  schedule:
   - cron: "0 3 * * *"

  push:
    branches:
      - 'master'

    tags:
      - '*'

  pull_request:
    branches:
      - '*'

jobs:
  AnghaSmallRun:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        llvm: ["11"]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    # https://stackoverflow.com/questions/58033366/how-to-get-current-branch-within-github-actions
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - name: Run against ${{ matrix.llvm }} (Pull Request)
      run: |
        tests/lifting-tools-ci/cloud/run-do-droplet.py --name "Rellic CI Run on PR" --script tests/ci-scripts/run-on-anghabench.sh --env-vars RUN_SIZE=1k,RELLIC_BRANCH=${BRANCH},LLVM_VERSION=${{ matrix.llvm }}
      env:
        SLACK_HOOK: ${{ secrets.SLACK_HOOK }}
        DO_TOKEN: ${{ secrets.DO_TOKEN }}
        BRANCH: ${{ github.head_ref }}
      if: github.event_name == 'pull_request'
    - name: Run against ${{ matrix.llvm }} (Push/Cron)
      run: |
        tests/lifting-tools-ci/cloud/run-do-droplet.py --name "Rellic CI Run" --script tests/ci-scripts/run-on-anghabench.sh --env-vars RUN_SIZE=1k,RELLIC_BRANCH=${BRANCH},LLVM_VERSION=${{ matrix.llvm }}
      env:
        SLACK_HOOK: ${{ secrets.SLACK_HOOK }}
        DO_TOKEN: ${{ secrets.DO_TOKEN }}
        BRANCH: ${{ steps.extract_branch.outputs.branch }}
      if: github.event_name != 'pull_request'
 