name: VCPKG Continuous Integration
on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    # run CI every day even if no PRs/merges occur
    - cron:  '0 6 * * *'

jobs:
  build_linux:
    strategy:
      fail-fast: false
      matrix:
        image:
          - { name: 'ubuntu', tag: '18.04' }
          - { name: 'ubuntu', tag: '20.04' }
        llvm: [
          '9',
          '10',
          '11'
          ]

    runs-on: ubuntu-20.04
    container:
      image: docker.pkg.github.com/trailofbits/cxx-common/vcpkg-builder-${{ matrix.image.name }}:${{ matrix.image.tag }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2
      - name: Install utility tools
        shell: bash
        run: |
          # TODO some of these should probably live in the Docker build image
          apt-get update
          apt-get install -y pixz xz-utils make

      - name: Build with build script
        shell: bash
        run: |
          ./scripts/build_with_vcpkg.sh --download-dir "$(pwd)/../pre-built-llvm-${{ matrix.llvm }}" --llvm-version ${{ matrix.llvm }}
          cmake --build rellic-build --target install
      - name: Tests
        shell: bash
        working-directory: rellic-build
        run: |
          # Test with CMake provided test
          env CTEST_OUTPUT_ON_FAILURE=1 cmake --build . --target test

          # Run tests manually (kinda ugly, so use CMake way)
          CLANG_BIN="$(find ../../pre-built-llvm-${{ matrix.llvm }} -name clang | grep "bin/clang")"
          ../scripts/roundtrip.py "./tools/rellic-decomp-${{ matrix.llvm }}.0" ../tests/tools/decomp "${CLANG_BIN}"

  build_mac:
    strategy:
      fail-fast: false
      matrix:
        os: [
          'macos-10.15',
          'macos-11.0'
          ]
        llvm: [
          '9',
          '10',
          '11'
          ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Build with build script
        shell: bash
        run: |
          ./scripts/build_with_vcpkg.sh --download-dir "$(pwd)/../pre-built-llvm-${{ matrix.llvm }}" --llvm-version ${{ matrix.llvm }}
          cmake --build rellic-build --target install
      - name: Tests
        shell: bash
        working-directory: rellic-build
        run: |
          # Test with CMake provided test
          env CTEST_OUTPUT_ON_FAILURE=1 cmake --build . --target test

          # Run tests manually (kinda ugly, so use CMake way)
          CLANG_BIN="$(find ../../pre-built-llvm-${{ matrix.llvm }} -name clang | grep "bin/clang")"
          ../scripts/roundtrip.py "./tools/rellic-decomp-${{ matrix.llvm }}.0" ../tests/tools/decomp "${CLANG_BIN}"
